image: node:20.18.0

definitions:
  scripts:
    setup-pnpm: &setup-pnpm npm install --global corepack@latest
      && corepack enable
      && corepack prepare pnpm@9.12.3 --activate

pipelines:
  branches:
    cms/push:
      - step:
          name: Build
          trigger: automatic
          script: [*setup-pnpm, pnpm install, pnpm build]
          artifacts:
            - dist/**

      - step:
          name: Deploy Hostinger SSH
          trigger: automatic
          deployment: production
          script:
            - pipe: atlassian/ftp-deploy:0.7.1
              variables:
                USER: $USER
                PASSWORD: $PASSWORD
                SERVER: $SERVER
                REMOTE_PATH: $REMOTE_PATH
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/dist'
          depends_on:
            - Build
