import { env } from "./env";

const SITE_TITLE = env.FRONTEND_SITE_TITLE;
const SITE_DESCRIPTION = env.FRONTEND_SITE_DESCRIPTION;
const SITE_URL = env.FRONTEND_SITE_URL;
const IS_LOCAL = env.FRONTEND_TINA_IS_LOCAL;
const BRANCH = env.BACKEND_GITHUB_BRANCH;
const IS_DEV_MODE = process.env.NODE_ENV !== "production";

export { IS_LOCAL, BRANCH, SITE_TITLE, SITE_DESCRIPTION, SITE_URL, IS_DEV_MODE };
