export const ESTADOS_BRASIL = [
  { value: '', label: 'Selecione o estado' },
  { value: 'Acre (AC)', label: 'Acre (AC)' },
  { value: 'Alagoas (AL)', label: 'Alagoas (AL)' },
  { value: 'Amapá (AP)', label: 'Amapá (AP)' },
  { value: 'Amazonas (AM)', label: 'Amazonas (AM)' },
  { value: 'Bahia (BA)', label: 'Bahia (BA)' },
  { value: 'Ceará (CE)', label: 'Ceará (CE)' },
  { value: 'Distrito Federal (DF)', label: 'Distrito Federal (DF)' },
  { value: 'Espírito Santo (ES)', label: 'Espírito Santo (ES)' },
  { value: 'Goiás (GO)', label: 'Goiás (GO)' },
  { value: 'Maranhão (MA)', label: 'Maranhão (MA)' },
  { value: 'Mato Grosso (MT)', label: 'Mato Grosso (MT)' },
  { value: 'Mato Grosso do Sul (MS)', label: 'Mato Grosso do Sul (MS)' },
  { value: 'Minas Gerais (MG)', label: 'Minas Gerais (MG)' },
  { value: 'Pará (PA)', label: 'Pará (PA)' },
  { value: 'Paraíba (PB)', label: 'Paraíba (PB)' },
  { value: 'Paraná (PR)', label: 'Paraná (PR)' },
  { value: 'Pernambuco (PE)', label: 'Pernambuco (PE)' },
  { value: 'Piauí (PI)', label: 'Piauí (PI)' },
  { value: 'Rio de Janeiro (RJ)', label: 'Rio de Janeiro (RJ)' },
  { value: 'Rio Grande do Norte (RN)', label: 'Rio Grande do Norte (RN)' },
  { value: 'Rio Grande do Sul (RS)', label: 'Rio Grande do Sul (RS)' },
  { value: 'Rondônia (RO)', label: 'Rondônia (RO)' },
  { value: 'Roraima (RR)', label: 'Roraima (RR)' },
  { value: 'Santa Catarina (SC)', label: 'Santa Catarina (SC)' },
  { value: 'São Paulo (SP)', label: 'São Paulo (SP)' },
  { value: 'Sergipe (SE)', label: 'Sergipe (SE)' },
  { value: 'Tocantins (TO)', label: 'Tocantins (TO)' },
];
