name: Deploy via FTP

on:
  workflow_dispatch:  # Só manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.12.3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.0'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      run: pnpm build

    - name: Deploy via FTP
      uses: modern-dev/ftp-mirror@v2
      with:
        server: ${{ vars.FTP_SERVER }}
        user: ${{ vars.FTP_USER }}
        password: ${{ vars.FTP_PASSWORD }}
        local_dir: "./dist"
        remote_dir: ${{ vars.FTP_REMOTE_PATH }}
        delete: "true"
        parallel: "10"
        force_ssl: "false"
        timeout: "600"