name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.12.3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.0'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Deploy to Hostinger via FTP
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ vars.FTP_SERVER }}
        user: ${{ vars.FTP_USER }}
        password: ${{ vars.FTP_PASSWORD }}
        localDir: ./dist/
        remoteDir: ${{ vars.FTP_REMOTE_PATH }}
        delete: true
        forceSsl: false
        max_retries: "2"