name: Build & Deploy to Hostinger

on:
  push:
    branches: [ cms/push ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.12.3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.0'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Deploy via FTP with clean slate
      env:
        FTP_SERVER: ${{ vars.FTP_SERVER }}
        FTP_USER: ${{ vars.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_REMOTE_PATH: ${{ vars.FTP_REMOTE_PATH }}
      run: |
        lftp -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER <<EOF
        set ftp:ssl-allow yes
        cd $FTP_REMOTE_PATH
        mirror --reverse --delete --only-newer --verbose ./dist/ ./
        bye
        EOF